# Generated by Django 4.1.2 on 2022-10-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=19)),
                ('emp_salary', models.ImageField(upload_to='')),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_designation', models.CharField(max_length=29)),
            ],
        ),
    ]
